// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterTrackerAPI.Data;

#nullable disable

namespace WaterTrackerAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231103233341_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WaterTrackerAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "dannymaher@gmail.com",
                            FirstName = "Danny",
                            LastName = "Maher"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sarahjenkins@gmail.com",
                            FirstName = "Sarah",
                            LastName = "Jenkins"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mikesmith@gmail.com",
                            FirstName = "Mike",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 4,
                            Email = "chloelee@gmail.com",
                            FirstName = "Chloe",
                            LastName = "Lee"
                        });
                });

            modelBuilder.Entity("WaterTrackerAPI.Entities.WaterIntake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumedWater")
                        .HasMaxLength(2147483647)
                        .HasColumnType("int");

                    b.Property<DateTime>("IntakeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("WaterIntake");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsumedWater = 5431,
                            IntakeDate = new DateTime(2023, 5, 1, 8, 30, 52, 0, DateTimeKind.Unspecified),
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            ConsumedWater = 10456,
                            IntakeDate = new DateTime(2023, 5, 3, 17, 24, 5, 0, DateTimeKind.Unspecified),
                            UserID = 1
                        },
                        new
                        {
                            Id = 3,
                            ConsumedWater = 2234,
                            IntakeDate = new DateTime(2023, 8, 12, 12, 36, 51, 0, DateTimeKind.Unspecified),
                            UserID = 1
                        },
                        new
                        {
                            Id = 4,
                            ConsumedWater = 67777,
                            IntakeDate = new DateTime(2023, 10, 23, 11, 17, 12, 0, DateTimeKind.Unspecified),
                            UserID = 1
                        },
                        new
                        {
                            Id = 5,
                            ConsumedWater = 9967,
                            IntakeDate = new DateTime(2023, 5, 1, 8, 30, 52, 0, DateTimeKind.Unspecified),
                            UserID = 2
                        },
                        new
                        {
                            Id = 6,
                            ConsumedWater = 14566,
                            IntakeDate = new DateTime(2023, 5, 3, 18, 24, 5, 0, DateTimeKind.Unspecified),
                            UserID = 2
                        },
                        new
                        {
                            Id = 7,
                            ConsumedWater = 23412,
                            IntakeDate = new DateTime(2023, 8, 15, 12, 36, 51, 0, DateTimeKind.Unspecified),
                            UserID = 2
                        },
                        new
                        {
                            Id = 8,
                            ConsumedWater = 17965,
                            IntakeDate = new DateTime(2023, 10, 23, 11, 17, 12, 0, DateTimeKind.Unspecified),
                            UserID = 2
                        },
                        new
                        {
                            Id = 9,
                            ConsumedWater = 89233,
                            IntakeDate = new DateTime(2023, 5, 1, 8, 30, 52, 0, DateTimeKind.Unspecified),
                            UserID = 3
                        },
                        new
                        {
                            Id = 10,
                            ConsumedWater = 445556,
                            IntakeDate = new DateTime(2023, 5, 3, 19, 24, 5, 0, DateTimeKind.Unspecified),
                            UserID = 3
                        },
                        new
                        {
                            Id = 11,
                            ConsumedWater = 1965,
                            IntakeDate = new DateTime(2023, 8, 15, 12, 36, 51, 0, DateTimeKind.Unspecified),
                            UserID = 3
                        },
                        new
                        {
                            Id = 12,
                            ConsumedWater = 38563,
                            IntakeDate = new DateTime(2023, 10, 22, 11, 17, 12, 0, DateTimeKind.Unspecified),
                            UserID = 3
                        },
                        new
                        {
                            Id = 13,
                            ConsumedWater = 56238,
                            IntakeDate = new DateTime(2023, 5, 1, 8, 30, 52, 0, DateTimeKind.Unspecified),
                            UserID = 4
                        },
                        new
                        {
                            Id = 14,
                            ConsumedWater = 77796,
                            IntakeDate = new DateTime(2023, 5, 3, 22, 24, 5, 0, DateTimeKind.Unspecified),
                            UserID = 4
                        },
                        new
                        {
                            Id = 15,
                            ConsumedWater = 32145,
                            IntakeDate = new DateTime(2023, 8, 15, 12, 36, 51, 0, DateTimeKind.Unspecified),
                            UserID = 4
                        },
                        new
                        {
                            Id = 16,
                            ConsumedWater = 93485,
                            IntakeDate = new DateTime(2023, 10, 21, 11, 17, 12, 0, DateTimeKind.Unspecified),
                            UserID = 4
                        });
                });

            modelBuilder.Entity("WaterTrackerAPI.Entities.WaterIntake", b =>
                {
                    b.HasOne("WaterTrackerAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
